### ISSUE TITLE
dotへのパス指定時にエラー発生

### ISSUE THREAD

**Issue by KatsuyaHiguchi** [hirokidaichi/guiflow#3]
素敵なツールをありがとうございます。
UI設計がはかどりそうです。

さて、以下の環境でdotへのパスを指定するステップで、エラーが発生しましたのでご報告致します。
対応方法を教えていただけると幸いです。

---

os: Windows7 64bit home premium / service pack 1
graphviz-2.38
入力したパス：C:\Graphviz2.38\bin\dot

エラー内容
![error](https://cloud.githubusercontent.com/assets/10562348/14307449/0fb0adfe-fc0a-11e5-8b83-b1a5963c5d9b.png)

**Comment by kazaoki** [comment]
作業が捗りそうなツールで素晴らしいです！
Windowsでも使えるとかなり嬉しいのですが、私も上記と同様のエラーが出てしまいました。（Win10 pro 64bit）
`uiflow.js` 84行目のSIGHUP でコケてる感じですが、ここらはやっぱり別途Windows対応が必要なんでしょうかね・・。

``` js
    setTimeout(function() {
        child.kill('SIGHUP');
    }, 50);
```

恐らくWindowsユーザーも相当数需要があるかと思いますので、ご対応いただけると嬉しいです・・！

**Comment by hirokidaichi** [comment]
graphvizへの依存自体を切ってみたので、このあたりばっさり削除しました。
また、windows10を購入したので、bootcampして試してみますね。

**Comment by kazaoki** [comment]
おおお！
graphviz無しでばっちり描画されてますね！
Windows10でも問題なしで動いています素晴らしいです！

**Comment by KatsuyaHiguchi** [comment]
ありがとうございます、動作を確認しました！
実際に使ってみるとこれは良いですね。
画面遷移の設計が楽しくなりそうです。
