### ISSUE TITLE
ファイル選択がフォルダを開くダイアログになっています。（Windows）

### ISSUE THREAD

**Issue by kazaoki** [hirokidaichi/guiflow#6]
Windows10 pro 64bit で確認しています。
File->Openメニュー、または `Ctrl+O` でファイル選択ダイアログを開くと、ファイルではなくフォルダの選択ダイアログが表示されるため、ファイルの選択ができません。。
![2016-04-08 17 01 43](https://cloud.githubusercontent.com/assets/6366870/14377707/2cd35622-fdac-11e5-847e-247adcdf6a89.png)

ちなみに、そのまま「フォルダを選択」すると、空の新規ウィンドウが表示されます。
お手数ですが、ご確認いただければと存じます。

**Comment by kazaoki** [comment]
#5 で同様の問題が投稿されておりましたので、こちら閉じます。
重複すいません。。

**Comment by yoku0825** [comment]
すぐ使いたくてうずうずしているWindowsおじさんたち :D

**Comment by kazaoki** [comment]
ｗｗ
